trigger:
- '*'

pool:
      name: RetoAzure
      demands:
      - agent.name -equals MyAgent

variables:
  buildConfiguration: 'Release'
  wwwrootDir: Tailspin.SpaceGame.Web/wwwroot

steps:
- task: UseDotNet@2
  displayName: 'Use .NET SDK 6.x.x'
  inputs:
    packageType: sdk
    version: '6.x'

# - task: Npm@1
#   displayName: 'Run npm install'
#   inputs:
#     verbose: false
- task: UseNode@1
  displayName: 'Install Node' 
  inputs:
    version: 16.x

- script: npm cache clean --force
  displayName: 'Clean NPM cache'

- task: Npm@1
  displayName: 'Run npm install'
  inputs:
    verbose: false
    arguments: --no-optional

- script: npx sass $(wwwrootDir) --no-source-map --style=compressed
  displayName: 'Compile Sass assets'

- script: npm install --global gulp-cli
  displayName: 'Install Gulp CLI globally'

- script: './node_modules/.bin/node-sass $(wwwrootDir) --output Tailspin.SpaceGame.Web/wwwroot'
  displayName: 'Compile Sass assets'

- task: gulp@1
  displayName: 'Run gulp tasks'

- script: 'echo "$(Build.DefinitionName), $(Build.BuildId), $(Build.BuildNumber)" > buildinfo.txt'
  displayName: 'Write build info'
  workingDirectory: Tailspin.SpaceGame.Web/wwwroot

- task: DotNetCoreCLI@2
  displayName: 'Restore project dependencies'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Build the project - Release'
  inputs:
    command: 'build'
    arguments: '--no-restore --configuration Release'
    projects: '**/*.csproj'